#!/usr/bin/env python3
"""
motherlode.py — the self-updating master blueprint generator
============================================================

Generates a complete, portable knowledge base of this site so it can be rebuilt
elsewhere by a human OR another AI:

  • MOTHERLODE.yaml — the SAME content in a structured, machine/AI-ingestible form
                      ("universal AI model language"). Valid YAML (also valid for
                      most JSON-ish parsers). This is the canonical transfer format.
  • MOTHERLODE.md   — the English playbook (architecture, every script, design
                      decisions, security posture, data model, roadmap, and a
                      step-by-step "rebuild this for a new site" guide).
  • llms.txt        — a short, LLM-facing index (the emerging 2026 convention) that
                      points other AIs at the blueprint and the key pages.

It scans the repo so the file inventory stays current, and its output is
DETERMINISTIC (no timestamps) so it only changes when the project actually changes
— no spurious daily commits. Stdlib only. Run any time:  python3 scripts/motherlode.py
"""
import re
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# ============================================================================
# THE BLUEPRINT — edit this to keep features & future changes documented.
# ============================================================================
BLUEPRINT = {
    "meta": {
        "name": "LobangKing.sg",
        "tagline": "Every Deal in Singapore — verified daily.",
        "type": "Static, automated, AI-assisted deals website",
        "blueprint_version": "1.0",
        "purpose_of_this_file": "Portable architecture + knowledge transfer for rebuilding this system on a new site.",
    },
    "stack": {
        "frontend": "Hand-written HTML + CSS + vanilla JS (no framework, no build for the browser)",
        "hosting": "GitHub Pages (free static hosting) + optional Cloudflare (WAF, headers, analytics)",
        "automation": "GitHub Actions (free scheduled jobs) — the 'backend' for a static site",
        "data": "A single JSON file (data/deals.json) acts as the database",
        "build": "Dependency-free Python (standard library only) — runs on the GitHub runner",
        "ai": "Optional server-side LLM enrichment + optional on-device browser AI (translation)",
    },
    "architecture": [
        "No server, no database, no framework — just files on a CDN. This is the core security + scaling advantage.",
        "GitHub Actions act as the backend: scheduled scripts fetch data, build pages, validate, and commit; GitHub Pages redeploys on each commit.",
        "Content is PRE-RENDERED into static HTML for SEO, then the same content is hydrated by JS for interactivity.",
        "Single sources of truth (category list, expiry parser, page builder) are imported across scripts so behaviour can't drift.",
    ],
    "components": [
        {"id": "pages", "files": "index.html, deals.html, about.html, submit.html, privacy.html, 404.html",
         "kind": "html", "purpose": "The site pages. Share one header/footer (generated by build_pages) and a strict CSP.",
         "notes": "Deal grids are pre-rendered between <!--DEALS-->/<!--SPOT--> markers then hydrated by main.js."},
        {"id": "design_system", "files": "css/styles.css (+ styles.min.css)", "kind": "css",
         "purpose": "Full design system: CSS custom-property tokens, light+dark themes, components, utilities.",
         "notes": "Minified to .min.css by minify.py during the build. No inline styles anywhere (CSP style-src 'self')."},
        {"id": "fonts", "files": "css/fonts.css, fonts/", "kind": "css",
         "purpose": "Self-hosted @font-face (Sora + DM Sans). No external font requests.",
         "notes": "Run scripts/get_fonts.sh once to download the woff2 files; falls back to system fonts until then."},
        {"id": "theme_boot", "files": "js/theme.js", "kind": "js",
         "purpose": "Sets light/dark on <html> before paint to avoid a flash. External file so the CSP can stay strict."},
        {"id": "core_js", "files": "js/main.js", "kind": "js",
         "purpose": "Render deals from JSON, live search/filter/sort, paginated 'load more', vote, share, copy code, theme toggle, mobile menu, back-to-top, service-worker registration.",
         "notes": "All HTML writes go through one Trusted-Types-safe sink (setHTML). Re-applies translation after re-render."},
        {"id": "web_vitals", "files": "js/vitals.js", "kind": "js",
         "purpose": "Core Web Vitals RUM (LCP/CLS/INP/TTFB) via PerformanceObserver. No external calls."},
        {"id": "engagement", "files": "js/engagement.js", "kind": "js",
         "purpose": "PWA install prompt + 'deals refreshed since your last visit' badge (return-visit drivers)."},
        {"id": "anti_copy", "files": "js/protect.js", "kind": "js",
         "purpose": "Deterrents: invisible content canary, console copyright notice, image drag/right-click block (images only)."},
        {"id": "translator", "files": "js/translate.js", "kind": "js",
         "purpose": "On-device AI translation (Chrome built-in Translator / Gemini Nano) into 中文/Malay/Tamil. Private, free, no API key. Progressive — hidden if unsupported."},
        {"id": "service_worker", "files": "sw.js", "kind": "js",
         "purpose": "Offline + instant repeat visits. Static assets cache-first; deals.json network-first. Bump CACHE name on asset change."},
        {"id": "aggregator", "files": "scripts/aggregate_deals.py", "kind": "py",
         "purpose": "DAILY: fetch deals from RSS feeds + per-brand Google News + optional affiliate API (concurrently), categorise across all categories, detect brands, parse expiry, dedupe, drop expired-at-fetch, optional AI polish, write deals.json.",
         "notes": "Never invents data; every deal keeps a source link. Single source of truth for CATEGORIES, BRANDS and parse_expiry."},
        {"id": "ai_enrich", "files": "scripts/ai_enrich.py", "kind": "py",
         "purpose": "OPTIONAL: polish titles/summaries/categories with any OpenAI-compatible LLM, using ONLY the fetched text (never invents). Safe no-op when unconfigured."},
        {"id": "builder", "files": "scripts/build_pages.py", "kind": "py",
         "purpose": "Single-source header/footer; pre-render deals + JSON-LD into HTML; generate per-deal (deal-<id>.html) and per-category (cat-<id>.html) SEO pages with Offer/ItemList schema; minify CSS; write feed.xml + sitemap.xml; render only ACTIVE (non-expired) deals; prune orphan pages."},
        {"id": "minifier", "files": "scripts/minify.py", "kind": "py",
         "purpose": "Conservative CSS minifier (comments + whitespace only — never removes meaningful spaces)."},
        {"id": "validator", "files": "scripts/validate.py", "kind": "py",
         "purpose": "HOURLY watchdog: validates JSON/XML, security/CSP compliance, asset integrity; runs the retention GC; rebuilds. Exits non-zero on compliance errors (alerts owner)."},
        {"id": "retention_gc", "files": "scripts/prune_pages.py", "kind": "py",
         "purpose": "Hard-deletes deals expired >10 days from the database, then rebuilds so the sitemap + per-deal pages auto-sync (new deals get URLs; expired/orphan pages deleted)."},
        {"id": "link_checker", "files": "scripts/check_links.py", "kind": "py",
         "purpose": "DAILY: removes deals whose outbound URL is definitively dead (404/410/451 only; ignores transient errors), then rebuilds."},
        {"id": "history", "files": "scripts/snapshot.py, history/", "kind": "py",
         "purpose": "DAILY: dated snapshot of deals.json + an added/removed change-log; prunes to the last 60 days (audit trail + rollback)."},
        {"id": "tests", "files": "scripts/test_aggregate.py", "kind": "py",
         "purpose": "Offline unit tests: parsing, expiry-drop, dedupe, categorisation, brand detection, AI no-op."},
        {"id": "config", "files": "scripts/sources.json, scripts/manual_deals.json", "kind": "config",
         "purpose": "sources.json: RSS feeds, brand watchlist, AI + affiliate toggles, settings. manual_deals.json: always-on curated deals."},
        {"id": "seo_files", "files": "robots.txt, sitemap.xml, feed.xml, manifest.webmanifest", "kind": "config",
         "purpose": "robots blocks AI/scraper bots (keeps search engines); sitemap+feed auto-generated; manifest = installable PWA."},
        {"id": "security_files", "files": "_headers, .well-known/security.txt", "kind": "config",
         "purpose": "_headers: full security header set for Cloudflare/Netlify (+ CSP report-only Trusted Types). security.txt: responsible-disclosure (RFC 9116)."},
        {"id": "ci_gates", "files": ".github/workflows/{lighthouse,a11y,codeql}.yml, .github/dependabot.yml, lighthouserc.json, .pa11yci.json", "kind": "ci",
         "purpose": "Quality/security gates: Lighthouse budget, pa11y WCAG-AA, CodeQL JS scan, auto-patched Actions."},
        {"id": "schedules", "files": ".github/workflows/{update-deals,validate,health-check,check-links}.yml", "kind": "ci",
         "purpose": "Scheduled jobs: daily deals build, hourly validate+GC, 30-min uptime ping, daily dead-link prune."},
    ],
    "security": {
        "csp": "default-src 'self'; script-src 'self'; style-src 'self' (NO unsafe-inline anywhere); connect/font/img/manifest/worker 'self'; form-action 'self' + formspree.io; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; upgrade-insecure-requests; report-to csp.",
        "trusted_types": "All DOM HTML writes go through one audited sink (setHTML) + a TrustedScriptURL policy for the SW. Shipped report-only; flip require-trusted-types-for 'script' into the enforced CSP after a browser test.",
        "headers": "HSTS preload, X-Frame-Options DENY, X-Content-Type-Options nosniff, Referrer-Policy, Permissions-Policy, COOP, CORP, CSP reporting endpoints.",
        "xss": "Every value escaped (esc) + link scheme-checked (safeUrl) before render; feed-sourced data treated as untrusted.",
        "secrets": "None in the browser. Affiliate/AI keys live only in GitHub Secrets, used server-side in Actions.",
        "anti_abuse": "Form honeypot + time-trap; AI/scraper bots blocked in robots; Cloudflare WAF/bot-fight/rate-limit recommended.",
        "anti_copy": "Honest stance: public content is copyable. Real moat = daily-rebuilt content (clones go stale in 24h) + canary + Cloudflare + DMCA.",
    },
    "data_model": {
        "file": "data/deals.json",
        "shape": "{ updated, categories[], brands_tracked[], brands_today[], deals[] }",
        "deal_fields": "id, title, store, categories[], icon, badges[{type,label}], access{type,label}, code?, desc, expiry, heat, url, source{name,url}, brand?, spotlight?",
        "categories": "all, food, electronics, home, travel, transport, fashion, entertainment, finance, online",
        "expiry_rule": "parse_expiry distinguishes start dates ('from'), end keywords ('till/until/ends'), ranges, single days; a deal is ACTIVE while end>=today.",
    },
    "patterns": [
        "Static site + CDN + GitHub Actions = a free, daily-fresh site that feels dynamic with zero server.",
        "Single source of truth: import CATEGORIES, parse_expiry and the builder everywhere so logic never drifts.",
        "Generate on the server (Actions), keep the browser lean; pre-render for SEO + hydrate for interactivity.",
        "Lock the CSP to 'self', make code Trusted-Types-ready, ship risky enforcement report-only first.",
        "Progressive enhancement: every advanced feature (translate, view transitions, scroll anim) degrades gracefully.",
        "Never fabricate data; if using AI, only summarise/translate REAL fetched text and keep the source link.",
        "Idempotent builders + diff-guarded commits + deterministic output = no spurious churn.",
        "Retention model: hide expired content immediately for UX, hard-delete after a grace window for the DB.",
        "An hourly validator that auto-fixes data and fails loudly on compliance regressions keeps the site honest.",
    ],
    "decisions": [
        {"choice": "Self-host fonts", "why": "Privacy + performance + lets the CSP drop external origins."},
        {"choice": "Remove all 'unsafe-inline'", "why": "A+ CSP; inline styles moved to utility classes."},
        {"choice": "Trusted Types report-only (not enforced)", "why": "Can't browser-test here; enforcing blindly could break JS for Chrome users. One-line flip after a DevTools check."},
        {"choice": "JSON file as database", "why": "No server needed; diffable, versioned, auditable in git."},
        {"choice": "Provider-agnostic AI (env-configured)", "why": "No vendor lock-in; free providers (GitHub Models/Groq/Gemini) swap via env."},
        {"choice": "Formspree for forms", "why": "Static sites can't process POST; one scoped form-action CSP exception."},
        {"choice": "Per-deal + category pages", "why": "Long-tail SEO — each deal becomes its own indexable URL."},
    ],
    "roadmap": [
        {"item": "Enforce Trusted Types (flip report-only → enforced)", "status": "ready — needs a browser DevTools check first"},
        {"item": "Per-deal Open Graph share images (Pillow)", "status": "designed; held back to avoid daily binary repo bloat"},
        {"item": "Auto-post new deals to a free Telegram channel (Bot API)", "status": "planned"},
        {"item": "Daily email digest builder (Buttondown/Brevo)", "status": "planned"},
        {"item": "On-device Summarizer + Prompt API 'deal assistant'", "status": "planned (Chrome built-in AI)"},
        {"item": "Web Push notifications for new deals", "status": "considered"},
        {"item": "Periodic Background Sync to refresh deals in the installed PWA", "status": "considered"},
        {"item": "Container queries + text-wrap:balance polish", "status": "considered"},
        {"item": "Cloudflare Web Analytics + Early Hints (103)", "status": "documented; one-click in Cloudflare"},
    ],
    "rebuild_for_new_site": [
        "1. Copy the repo structure (scripts/, js/, css/, .github/, pages, config files).",
        "2. Rebrand: replace the logo and run the icon generator; change --navy/--gold tokens in css/styles.css; set SITE_URL + name in scripts/build_pages.py and aggregate_deals.py.",
        "3. Re-point the data source: edit scripts/sources.json (RSS feeds, brand watchlist) — or replace fetch_rss with your own domain's data source.",
        "4. Adjust CATEGORIES and BRANDS in scripts/aggregate_deals.py to the new niche.",
        "5. Rewrite the page copy (hero, about, privacy) and the JSON-LD names.",
        "6. Set integrations: Formspree form ID, social handles (SOCIALS in build_pages), security.txt contact, and optional AI/affiliate GitHub Secrets.",
        "7. Deploy: push to GitHub, enable Pages (deploy from branch / root), enable Actions, optionally put Cloudflare in front.",
        "8. Verify: run scripts/test_aggregate.py, scripts/build_pages.py and scripts/validate.py; then let the daily/hourly workflows take over.",
    ],
}


# ============================================================================
# Minimal, dependency-free YAML emitter (output is valid YAML; strings are
# JSON-quoted, which YAML accepts — guarantees correctness without PyYAML).
# ============================================================================
def _scalar(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return json.dumps(str(v), ensure_ascii=False)


def to_yaml(obj, indent=0):
    pad = "  " * indent
    out = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            if isinstance(v, (dict, list)) and v:
                out.append(f"{pad}{k}:")
                out.append(to_yaml(v, indent + 1))
            else:
                out.append(f"{pad}{k}: {_scalar(v)}")
    elif isinstance(obj, list):
        for item in obj:
            if isinstance(item, dict):
                inner = to_yaml(item, indent + 1).split("\n")
                out.append(f"{pad}- {inner[0].lstrip()}")
                out.extend(inner[1:])
            else:
                out.append(f"{pad}- {_scalar(item)}")
    return "\n".join(out)


# ============================================================================
# Live inventory scan (keeps the file list current)
# ============================================================================
SELF_OUTPUTS = {"MOTHERLODE.yaml", "MOTHERLODE.md", "llms.txt"}


def inventory():
    # Exclude this script's own generated outputs so the count is stable across runs.
    files = [p for p in ROOT.rglob("*") if p.is_file()
             and "__pycache__" not in p.parts and not p.name.startswith(".DS")
             and p.name not in SELF_OUTPUTS]
    by_dir = {}
    for p in files:
        rel = p.relative_to(ROOT)
        top = rel.parts[0] if len(rel.parts) > 1 else "(root)"
        by_dir[top] = by_dir.get(top, 0) + 1
    return {
        "total_files": len(files),
        "by_directory": dict(sorted(by_dir.items())),
        "generated": {
            "per_deal_pages": len(list(ROOT.glob("deal-*.html"))),
            "category_pages": len(list(ROOT.glob("cat-*.html"))),
            "history_snapshots": len(list((ROOT / "history").glob("deals-*.json"))) if (ROOT / "history").exists() else 0,
        },
    }


# ============================================================================
# English Markdown rendering (same content, human-facing)
# ============================================================================
def render_md(bp):
    m = bp["meta"]
    L = [f"# 🜲 MOTHERLODE — {m['name']} blueprint", "",
         f"> {m['tagline']}  ", f"> **{m['type']}** · blueprint v{m['blueprint_version']}", "",
         "This is the master knowledge base for this site — written so a human **or another AI**",
         "can rebuild the whole system on a new site. The machine-readable twin is",
         "[`MOTHERLODE.yaml`](MOTHERLODE.yaml); an LLM index is [`llms.txt`](llms.txt).", "",
         "## Stack"]
    for k, v in bp["stack"].items():
        L.append(f"- **{k}**: {v}")
    L += ["", "## Architecture"]
    L += [f"- {a}" for a in bp["architecture"]]
    L += ["", "## Components"]
    for c in bp["components"]:
        L.append(f"### `{c['files']}`")
        L.append(f"_{c['kind']}_ — {c['purpose']}")
        if c.get("notes"):
            L.append(f"  ↳ {c['notes']}")
        L.append("")
    L += ["## Security posture"]
    for k, v in bp["security"].items():
        L.append(f"- **{k}**: {v}")
    L += ["", "## Data model"]
    for k, v in bp["data_model"].items():
        L.append(f"- **{k}**: {v}")
    L += ["", "## Reusable patterns"]
    L += [f"- {p}" for p in bp["patterns"]]
    L += ["", "## Key decisions"]
    L += [f"- **{d['choice']}** — {d['why']}" for d in bp["decisions"]]
    L += ["", "## Roadmap / future changes"]
    L += [f"- [{d['status']}] {d['item']}" for d in bp["roadmap"]]
    L += ["", "## Rebuild this for a NEW site"]
    L += bp["rebuild_for_new_site"]
    inv = bp["inventory"]
    L += ["", "## Live inventory (auto-scanned)",
          f"- **Total files:** {inv['total_files']}",
          f"- **Generated:** {inv['generated']['per_deal_pages']} per-deal pages, "
          f"{inv['generated']['category_pages']} category pages, "
          f"{inv['generated']['history_snapshots']} history snapshots",
          "- **By directory:** " + ", ".join(f"{k} ({v})" for k, v in inv["by_directory"].items()), ""]
    L += ["---", "_Regenerate with `python3 scripts/motherlode.py` (also runs in the daily build). "
          "Edit the `BLUEPRINT` in `scripts/motherlode.py` to document new features or roadmap items._"]
    return "\n".join(L) + "\n"


def render_llms_txt(bp):
    m = bp["meta"]
    return (f"# {m['name']}\n\n> {m['tagline']}\n\n"
            f"{m['type']}. Full machine-readable architecture blueprint for rebuilding or "
            f"understanding this system is in MOTHERLODE.yaml (structured) and MOTHERLODE.md (English).\n\n"
            "## Key docs\n"
            "- [Blueprint (structured)](MOTHERLODE.yaml): every component, script, security control, data model, roadmap.\n"
            "- [Blueprint (English)](MOTHERLODE.md): the same, as a rebuild playbook.\n"
            "- [README](README.md): deploy + operations.\n"
            "- [Security](SECURITY.md): threat model + hardening.\n\n"
            "## Site\n"
            "- [All deals](deals.html) · [About](about.html) · [Submit a deal](submit.html)\n"
            "- Deals data: [deals.json](data/deals.json) · Feed: [feed.xml](feed.xml)\n")


def main():
    bp = dict(BLUEPRINT)
    bp["inventory"] = inventory()
    (ROOT / "MOTHERLODE.yaml").write_text(
        "# MOTHERLODE — structured blueprint (AI-ingestible). Generated by scripts/motherlode.py.\n"
        + to_yaml(bp) + "\n", encoding="utf-8")
    (ROOT / "MOTHERLODE.md").write_text(render_md(bp), encoding="utf-8")
    (ROOT / "llms.txt").write_text(render_llms_txt(bp), encoding="utf-8")
    print(f"Motherlode updated — {bp['inventory']['total_files']} files documented "
          f"→ MOTHERLODE.yaml, MOTHERLODE.md, llms.txt")


if __name__ == "__main__":
    main()
